# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-18 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgURL', models.CharField(max_length=400)),
                ('caption', models.TextField(default='')),
                ('postDate', models.DateField()),
            ],
        ),
    ]
